config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pets do

  end

  root 'pets#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pets
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  has_attached_file :pet_img, :styles => { :pet_index => "250x250>", :pet_show => "300x300>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :pet_img, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pets

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
before_action :find_pet, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @pets = Pet.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @pets = Pet.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @pet = current_user.pets.build
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
		@pet = current_user.pets.build(pet_params)
		@pet.category_id = params[:category_id]

		if @pet.save
			redirect_to root_path
		else
			render 'new'
		end

    # if @pet.save
    #   render json: @pet
    # else
    #   render json: {
    #           error: {
    #             message: @todo.errors.full_messages.to_sentence
    #           }
    #   }
    # end
	 end

  def edit
      @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
      @categories = Category.all.map { |c| [c.name, c.id] }
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
        render 'edit'
  end
end

  def destroy
    @pet.destroy
    redirect_to root_path

    # render json: {
    #     message: "GONE!"
    # }
  end



private

  def pet_params
    params.require(:pet).permit(:report, :description, :where_specifics, :author, :category_id, :pet_img, :petname, :breed, :type, :size, :gender, :age, :lastseen, :owner, :phone)

  end

  def find_pet
    @pet = Pet.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Lost Pet</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

<body>

  <nav class="navbar navbar-default">
		  <div class="container">
			    <div class="navbar-header">
				      <%= link_to "Lost Pet", root_path, class: "navbar-brand" %>
			    </div>

			    <ul class="nav navbar-nav navbar-right">
				      <li><%= link_to "Sign Up", new_user_registration_path %></li>
				      <% if user_signed_in? %>
					    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>

              <% else %>
					    <li><%= link_to "Log In", new_user_session_path %></li>
				      <% end %>
			    </ul>


          <ul class="nav navbar-nav navbar-left">
              <li class="dropdown">
    					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>

              <ul class="dropdown-menu" role="menu">
    						  <% Category.all.each do |category| %>
    							<li class="<%= 'active' if params[:category] == category.name %>">
    							<%= link_to category.name, pets_path(category: category.name), class: "link" %>
    							</li>
    						  <% end %>
    					</ul>
    		      </li>

              <% if user_signed_in? %>
              <li><%= link_to "Add Pet", new_pet_path %></li>
              <% end %>

            </ul>
        </div>

    </nav>

  <center>  <p class="notice"><%= notice %></p></center>
  <center>    <p class="alert"><%= alert %></p></center>

      <div class="container">

    <%= yield %>


    </div>



<div class="footer">Joanthan Li and Pin Lu</div>



  </body>
</html>

app/views/pets/_form.html.erb
<div class="main">
  <h1>Post a report</h1>
    <%= simple_form_for @pet do |f| %>

      <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %><br />
      <%= f.file_field :pet_img %><br />
      <h4><%= f.input :petname %><br /></h4>
      <%= f.input :breed %><br />

      <%= f.input :color %><br />
      <%= f.input :size %><br />
      <%= f.input :gender %><br />
      <%= f.input :age %><br />
      <%= f.input :lastseen %><br />
      <%= f.input :phone %>
      <!-- <%= f.input :report, label: "Report Title" %> -->
      <%= f.input :description %>
      <!-- <%= f.input :where_specifics %> -->
      <!-- <%= f.input :author %> -->
      <!-- <%= f.input :email %> -->

      <%= f.button :submit %>

    <% end %>

</div>
</div>

app/views/pets/edit.html.erb
<center><h1>Update</h1></center>


<div class ="row">
  <div class="col-md-4">
    <%= simple_form_for @pet, :html => { :multipart => true } do |f| %>

      <%= image_tag @pet.pet_img.url(:pet_show), class: "pet-show" %>
      <br>
      <%= f.select :category_id, @categories %>
      <%= f.file_field :pet_img %>
  </div>

  <div class="col-md-8">

    <h3><%= f.input :petname %><h3>
    <h4><%= f.input :breed %><h4>
    <h4><%= f.input :color %><h4>
    <h4><%= f.input :size %><h4>
    <h4><%= f.input :gender %><h4>
    <h4><%= f.input :age %><h4>
    <h4><%= f.input :lastseen %><h4>
    <h4><%= f.input :description %><h4>
    <h4><%= f.input :owner %><h4>
    <h4><%= f.input :phone %><h4>
    <Br>
    <h4><%= f.button :submit %><h4>
<% end %>
</div>
</div>

app/views/pets/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @pets.count == 0 %>

	<h2>There are no pets currently in this category.</h2>

  <% else %>

		<div class="row">

<% @pets.each do |pet| %>
<h2><%= pet.report %></h2>

<div class="col-md-3">

<a href="/pets/<%= pet.id %>">
					<%= image_tag pet.pet_img.url(:pet_index), class: "pet" %>

				</a>
			</div>

<% end %>
</div>

<% end %>

app/views/pets/new.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

<%= render 'form' %> 

app/views/pets/show.html.erb
<div class ="row">

<div class="col-md-4">
<%= image_tag @pet.pet_img.url(:pet_show), class: "pet-show" %>
</div>

	<div class="col-md-8">
<h2>Pet Name: <%= @pet.petname %></h2>
<h3>Breed: <%= @pet.breed %></h3>
<h3>Color: <%= @pet.color %></h3>
<h3>Size: <%= @pet.size %></h3>
<h3>Gender: <%= @pet.gender %></h3>
<h3>Age: <%= @pet.age %></h3>
<h3>Last Seen: <%= @pet.lastseen %></h3>
<h3>Description: <%= @pet.description %></h3>
<h3>Name: <%= @pet.owner %></h3>
<h3>Phone: <%= @pet.phone %></h3>
	</div>





<div class ="row">

<div class="col-md-4">
<!-- where the review and rating wil go  -->
</div>
</div>

<center>
<%= link_to "Back", root_path %>

<% if user_signed_in? %>

<% if @pet.user_id == current_user.id %>

  <%= link_to "Edit", edit_pet_path(@pet) %>
  <%= link_to "Delete", pet_path(@pet), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
<% end %>
<% end %>
</center>